// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;
import static org.junit.Assert.assertThat;

public class SearchObjectsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "Drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get("https://www.agora.co.il/");
    driver.manage().window().setSize(new Dimension(1600, 860));


    {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("#dialog_overlayTd > div > div.dialog_closeButton")));
    driver.findElement(By.cssSelector("#dialog_overlayTd > div > div.dialog_closeButton")).click();
    }


  }
  @After
  public void tearDown() {
    driver.close();
    driver.quit();
  }
  @Test
  public void searchWithOutValue() {

    driver.findElement(By.cssSelector(".pinkButton")).click();
    driver.findElement(By.id("pinkPageTitle")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("חפצי יד שניה חדשים באתר"));

  }
  @Test
  public void searchByCategories() {
    driver.findElement(By.id("toggleAdvancedSearch")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // Wait for categoryBarInput to be present
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("categoryBarInput")));

    // Click the categoryBarInput to open the dropdown
    driver.findElement(By.id("categoryBarInput")).click();

    // Wait for the category 'מוצרי חשמל' option to become visible
    WebElement categoryOption = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//option[. = 'מוצרי חשמל']")));

    // Scroll the category option into view
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", categoryOption);

    // Click the category option
    categoryOption.click();

    // Wait for subcategoryBarInput to be present
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("subcategoryBarInput")));

    // Click the subcategoryBarInput to open the subcategory dropdown
    driver.findElement(By.id("subcategoryBarInput")).click();

    // Wait for the subcategory option to become visible
    WebElement subcategoryOption = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//option[. = '-- טוסטרים וטוסטר אובן']")));

    // Scroll the subcategory option into view
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", subcategoryOption);

    // Click the subcategory option
    subcategoryOption.click();

    // Wait for conditionBarInput to be present
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("conditionBarInput")));

    // Click the conditionBarInput to open the condition dropdown
    driver.findElement(By.id("conditionBarInput")).click();

    // Wait for the condition option to become visible
    WebElement conditionOption = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//option[. = 'מעט פגום ומעלה']")));

    // Scroll the condition option into view
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", conditionOption);

    // Click the condition option
    conditionOption.click();

    // Click the pinkButton
    driver.findElement(By.cssSelector(".pinkButton")).click();

    // Wait for pinkPageTitle to be present
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("pinkPageTitle")));

    // Click the pinkPageTitle
    driver.findElement(By.id("pinkPageTitle")).click();

    // Assertions
    assertThat(driver.findElement(By.cssSelector("#pinkPageTitle > a:nth-child(1)")).getText(), is("מוצרי חשמל"));
    assertThat(driver.findElement(By.cssSelector(".criteriaField:nth-child(3) > .searchFieldTitle")).getText(), is("תת קטגוריה:"));
  }

  @Test
  public void searchByName() {
    driver.findElement(By.id("tags")).click();
    driver.findElement(By.id("tags")).sendKeys("מקרר");
    driver.findElement(By.cssSelector(".pinkButton")).click();
    driver.findElement(By.id("pinkPageTitle")).click();
    assertThat(driver.findElement(By.id("searchTermsInfo")).getText(), is("תוצאות חיפוש עבור: מקרר"));
  }
  @Test
  public void searchByCity() {
    driver.findElement(By.id("takeCityBarInput")).click();
    driver.findElement(By.id("takeCityBarInput")).sendKeys("אשדוד");
    driver.findElement(By.cssSelector(".pinkButton")).click();
    driver.findElement(By.id("pinkPageTitle")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("חפצי יד שניה באשדוד"));
  }
  @Test
  public void searchWithImage() {
    driver.findElement(By.id("toggleAdvancedSearch")).click();
    driver.findElement(By.id("picOnly")).click();
    driver.findElement(By.cssSelector(".pinkButton")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".objectGroup:nth-child(2) .photoIcon span"));
      assert(elements.size() > 0);
    }

  }
  @Test
  public void advancedSearchButtonValidation() {
    driver.findElement(By.id("toggleAdvancedSearch")).click();
    assertThat(driver.findElement(By.id("toggleAdvancedSearch")).getText(), is("חיפוש פשוט"));

  }
}
